# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picface',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_detected',
            field=models.IntegerField(default=0),
        ),
    ]
