# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170831_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
