# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170901_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='s_picname',
            field=models.CharField(max_length=150),
        ),
    ]
