# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170901_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picname',
        ),
        migrations.AlterField(
            model_name='face',
            name='s_picname',
            field=models.ImageField(upload_to='PIC'),
        ),
    ]
