# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170901_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='s_picname',
            new_name='show_pic',
        ),
        migrations.RemoveField(
            model_name='picface',
            name='picname',
        ),
        migrations.AddField(
            model_name='picface',
            name='is_identified',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='picface',
            name='source_pic',
            field=models.ImageField(default='', upload_to='PIC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='face',
            name='face_info',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='picface',
            name='pic',
            field=models.ImageField(upload_to='SMALL'),
        ),
        migrations.AlterField(
            model_name='picface',
            name='uid',
            field=models.CharField(default='', max_length=150),
        ),
    ]
