# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170902_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
