# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_face_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='picface',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='is_deleted',
        ),
    ]
